/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.projectkel8;

public class dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JenisKaryawan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        buttonAbsensi = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        inputNama = new javax.swing.JTextField();
        inputTunjangan = new javax.swing.JTextField();
        inputGajiPokok = new javax.swing.JTextField();
        boxJabatan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        buttonTambah = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        buttonKembaliLogin = new javax.swing.JButton();
        KaryawanTetap = new javax.swing.JRadioButton();
        KaryawanKontak = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DATA KARYAWAN");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        buttonAbsensi.setBackground(new java.awt.Color(153, 204, 255));
        buttonAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonAbsensi.setForeground(new java.awt.Color(255, 255, 255));
        buttonAbsensi.setText("ABSENSI ");
        buttonAbsensi.addActionListener(this::buttonAbsensiActionPerformed);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 102));
        jButton3.setText("CETAK SLIP GAJI");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM INPUT KARYAWAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Karyawan :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jabatan :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Departemen :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gaji Pokok :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tunjangan :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jenis Kayawan");

        inputId.setText("Input id");
        inputId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputIdFocusLost(evt);
            }
        });
        inputId.addActionListener(this::inputIdActionPerformed);
        inputId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputIdKeyTyped(evt);
            }
        });

        inputNama.setText("Input nama");
        inputNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNamaFocusLost(evt);
            }
        });
        inputNama.addActionListener(this::inputNamaActionPerformed);
        inputNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNamaKeyTyped(evt);
            }
        });

        inputTunjangan.addCaretListener(this::inputTunjanganCaretUpdate);
        inputTunjangan.addActionListener(this::inputTunjanganActionPerformed);
        inputTunjangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTunjanganKeyTyped(evt);
            }
        });

        inputGajiPokok.addCaretListener(this::inputGajiPokokCaretUpdate);
        inputGajiPokok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputGajiPokokFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputGajiPokokFocusLost(evt);
            }
        });
        inputGajiPokok.addActionListener(this::inputGajiPokokActionPerformed);
        inputGajiPokok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputGajiPokokKeyTyped(evt);
            }
        });

        boxJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Jabatan--", "Supervisor", "Senior", "Reguler", "Magang" }));
        boxJabatan.addActionListener(this::boxJabatanActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "Nama Karyawan", "Jabatan", "Departemen", "Jenis Karyawan", "Gaji Pokok", "Tunjangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Departemen--", "HRD", "Finance & Accounting", "Marketing & Sales", "Operasional & Produksi", "IT" }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        buttonTambah.setBackground(new java.awt.Color(255, 255, 102));
        buttonTambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonTambah.setForeground(new java.awt.Color(255, 102, 102));
        buttonTambah.setText("Tambah");
        buttonTambah.setActionCommand("+Tambah");
        buttonTambah.addActionListener(this::buttonTambahActionPerformed);

        buttonReset.setBackground(new java.awt.Color(255, 255, 102));
        buttonReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonReset.setForeground(new java.awt.Color(255, 102, 102));
        buttonReset.setText("Reset");
        buttonReset.setActionCommand("+Tambah");
        buttonReset.addActionListener(this::buttonResetActionPerformed);

        buttonSimpan.setBackground(new java.awt.Color(255, 255, 102));
        buttonSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(255, 102, 102));
        buttonSimpan.setText("Simpan");
        buttonSimpan.setActionCommand("+Tambah");
        buttonSimpan.addActionListener(this::buttonSimpanActionPerformed);

        buttonKembaliLogin.setBackground(new java.awt.Color(255, 51, 51));
        buttonKembaliLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonKembaliLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembaliLogin.setText("Kembali");
        buttonKembaliLogin.addActionListener(this::buttonKembaliLoginActionPerformed);

        JenisKaryawan.add(KaryawanTetap);
        KaryawanTetap.setText("Tetap");
        KaryawanTetap.addActionListener(this::KaryawanTetapActionPerformed);

        JenisKaryawan.add(KaryawanKontak);
        KaryawanKontak.setText("Kontrak");
        KaryawanKontak.addActionListener(this::KaryawanKontakActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rp");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel9)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(inputId, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inputNama, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boxJabatan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jComboBox2, 0, 1, Short.MAX_VALUE)
                                                .addGap(258, 258, 258))
                                            .addComponent(inputGajiPokok))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(KaryawanTetap, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(KaryawanKontak, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputTunjangan)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonAbsensi)
                        .addGap(29, 29, 29)
                        .addComponent(buttonKembaliLogin)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3)
                        .addGap(233, 233, 233))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAbsensi)
                    .addComponent(buttonKembaliLogin)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(boxJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KaryawanTetap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KaryawanKontak)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(inputGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(inputTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbsensiActionPerformed
        // TODO add your handling code here:
        Presensi absen = new Presensi();
        absen.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_buttonAbsensiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxJabatanActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void inputGajiPokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGajiPokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGajiPokokActionPerformed

    private void inputTunjanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganActionPerformed

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputIdFocusGained
        // TODO add your handling code here:
        if (inputId.getText().equals("Input id")){
            inputId.setText("");
            inputId.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_inputIdFocusGained

    private void inputIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputIdFocusLost
        // TODO add your handling code here:
        if (inputId.getText().trim().isEmpty()){
            inputId.setText("Input id");
            inputId.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_inputIdFocusLost

    private void inputNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNamaFocusGained
        // TODO add your handling code here:
            if (inputNama.getText().equals("Input nama")){
            inputNama.setText("");
            inputNama.setForeground(java.awt.Color.BLACK);
        }
    
    }//GEN-LAST:event_inputNamaFocusGained

    private void inputNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNamaFocusLost
        // TODO add your handling code here:
        if (inputNama.getText().trim().isEmpty()){
            inputNama.setText("Inputvid");
            inputNama.setForeground(new java.awt.Color(204, 204, 204));
        }
    
    }//GEN-LAST:event_inputNamaFocusLost

    private void inputIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputIdKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != ' ' && c != java.awt.event.KeyEvent.VK_BACK_SPACE && c != java.awt.event.KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_inputIdKeyTyped

    private void inputNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNamaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ' && c != java.awt.event.KeyEvent.VK_BACK_SPACE && c != java.awt.event.KeyEvent.VK_DELETE) {
        evt.consume(); // Tolak karakter selain huruf dan spasi
    }
    }//GEN-LAST:event_inputNamaKeyTyped

    private void inputGajiPokokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputGajiPokokKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String currentText = inputGajiPokok.getText();
        if (!currentText.startsWith(". ")){
            inputGajiPokok.setText(". ");
            
        }
        if (inputGajiPokok.getCaretPosition() <= 4 && (c==java.awt.event.KeyEvent.VK_BACK_SPACE || c == java.awt.event.KeyEvent.VK_DELETE)){
        evt.consume();
        return;
    }
        
        if(!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE && c!= java.awt.event.KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_inputGajiPokokKeyTyped

    private void inputGajiPokokCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_inputGajiPokokCaretUpdate
        // TODO add your handling code here:
        
        if (inputGajiPokok.getCaretPosition() < 4){
           inputGajiPokok.setCaretPosition(4);
        }
    }//GEN-LAST:event_inputGajiPokokCaretUpdate

    private void inputTunjanganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTunjanganKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String currentText = inputTunjangan.getText();
        if (!currentText.startsWith(". ")){
            inputTunjangan.setText(". ");
            
        }
        if (inputTunjangan.getCaretPosition() <= 4 && (c==java.awt.event.KeyEvent.VK_BACK_SPACE || c == java.awt.event.KeyEvent.VK_DELETE)){
        evt.consume();
        return;
    }
        
        if(!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE && c!= java.awt.event.KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_inputTunjanganKeyTyped

    private void inputTunjanganCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_inputTunjanganCaretUpdate
        // TODO add your handling code here:
        
        if (inputGajiPokok.getCaretPosition() < 4){
           inputGajiPokok.setCaretPosition(4);
        }
    }//GEN-LAST:event_inputTunjanganCaretUpdate

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
    String id = inputId.getText().trim();
    String nama = inputNama.getText().trim();
    String jabatan = (String) boxJabatan.getSelectedItem();
    String departemen = (String) jComboBox2.getSelectedItem();
    String gajiText = inputGajiPokok.getText().trim();
    String tunjanganText = inputTunjangan.getText().trim();
    String jenisKaryawan = "";

    // Validasi ID
    if (id.isEmpty() || id.equals("Input id")) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "ID Karyawan tidak boleh kosong!", "Peringatan",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validasi Nama
    if (nama.isEmpty() || nama.equals("Input nama")) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Nama Karyawan tidak boleh kosong!", "Peringatan",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validasi Jabatan
    if (jabatan.equals("--Jabatan--")) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Pilih Jabatan terlebih dahulu!", "Peringatan",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validasi Departemen
    if (departemen.equals("--Departemen--")) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Pilih Departemen terlebih dahulu!", "Peringatan",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validasi Jenis Karyawan
    if (!KaryawanTetap.isSelected() && !KaryawanKontak.isSelected()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Pilih Jenis Karyawan terlebih dahulu!", "Peringatan",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    jenisKaryawan = KaryawanTetap.isSelected() ? "Tetap" : "Kontrak";

    // Parse Gaji Pokok
    double gajiPokok = 0;
    try {
        String gajiAngka = gajiText.replace(".", "").replace(". ", "").trim();
        if (gajiAngka.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Gaji Pokok tidak boleh kosong!", "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        gajiPokok = Double.parseDouble(gajiAngka);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Format Gaji Pokok tidak valid!", "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Parse Tunjangan (hanya jika Tetap / field aktif)
    double tunjangan = 0;
    if (inputTunjangan.isEnabled()) {
        try {
            String tunjanganAngka = tunjanganText.replace("Rp.", "").replace("Rp. ", "").trim();
            if (!tunjanganAngka.isEmpty()) {
                tunjangan = Double.parseDouble(tunjanganAngka);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Format Tunjangan tidak valid!", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    // Tambahkan baris ke tabel
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{
        Integer.parseInt(id), nama, jabatan, departemen,
        jenisKaryawan, gajiPokok, tunjangan
    });

    javax.swing.JOptionPane.showMessageDialog(this,
        "Data karyawan berhasil ditambahkan!", "Berhasil",
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
    inputId.setText("Input id");
    inputId.setForeground(new java.awt.Color(204, 204, 204));

    inputNama.setText("Input nama");
    inputNama.setForeground(new java.awt.Color(204, 204, 204));

    // Reset ComboBox
    boxJabatan.setSelectedIndex(0);
    jComboBox2.setSelectedIndex(0);

    // Reset RadioButton
    JenisKaryawan.clearSelection();

    // Reset Gaji & Tunjangan
    inputGajiPokok.setText(". ");
    inputTunjangan.setText(". ");
    inputTunjangan.setEnabled(true);
    inputTunjangan.setBackground(java.awt.Color.WHITE);
    inputTunjangan.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();

    // Hitung baris yang tidak kosong
    int jumlahData = 0;
    for (int i = 0; i < model.getRowCount(); i++) {
        if (model.getValueAt(i, 1) != null) {
            jumlahData++;
        }
    }

    if (jumlahData == 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Tidak ada data untuk disimpan!", "Peringatan",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    javax.swing.JOptionPane.showMessageDialog(this,
        jumlahData + " data karyawan telah tersimpan!", "Simpan Berhasil",
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonKembaliLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliLoginActionPerformed
        // TODO add your handling code here:
        LoginPage login = new LoginPage();
        login.setVisible(true);
        
        this.dispose();
                       
    }//GEN-LAST:event_buttonKembaliLoginActionPerformed

    private void KaryawanTetapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaryawanTetapActionPerformed
        // TODO add your handling code here:
    inputTunjangan.setEnabled(true);
    inputTunjangan.setBackground(java.awt.Color.WHITE);
    inputTunjangan.setText(" ");
    inputTunjangan.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_KaryawanTetapActionPerformed

    private void KaryawanKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaryawanKontakActionPerformed
        // TODO add your handling code here:
    inputTunjangan.setEnabled(false);
    inputTunjangan.setText("0.");
    inputTunjangan.setBackground(new java.awt.Color(204, 204, 204));
    inputTunjangan.setForeground(java.awt.Color.GRAY);
        
    }//GEN-LAST:event_KaryawanKontakActionPerformed

    private void inputGajiPokokFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputGajiPokokFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGajiPokokFocusGained

    private void inputGajiPokokFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputGajiPokokFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGajiPokokFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JenisKaryawan;
    private javax.swing.JRadioButton KaryawanKontak;
    private javax.swing.JRadioButton KaryawanTetap;
    private javax.swing.JComboBox<String> boxJabatan;
    private javax.swing.JButton buttonAbsensi;
    private javax.swing.JButton buttonKembaliLogin;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JTextField inputGajiPokok;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputTunjangan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}

