/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectkel8;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Presensi extends javax.swing.JFrame {
    
    private static Connection mysqlconfig;
    
    public static Connection configDB()throws SQLException 
    {
        try {
            String url="jdbc:mysql://localhost:3306/data_presensi";
            String user="roat";
            String pass="";
            
            DriverManager.registerDriver (new com.mysql.cj.jdbc.Driver());
            mysqlconfig = DriverManager.getConnection(url, user, pass);
        }
        catch (Exception e)
        {
            System.err.println("Koneksi gagal "+e.getMessage());
        }
        return mysqlconfig;
    }
            
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Presensi.class.getName());

    /**
     * Creates new form absensi
     */
    public Presensi() {
        initComponents();
        load_table();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        buttonKembaliDB = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buttonKembaliDB1 = new javax.swing.JButton();
        buttonKembaliDB2 = new javax.swing.JButton();
        buttonKembaliDB3 = new javax.swing.JButton();
        buttonKembaliDB4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jTextField1.setText("*YYYY-MM-DD");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        buttonKembaliDB.setBackground(new java.awt.Color(153, 153, 255));
        buttonKembaliDB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonKembaliDB.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembaliDB.setText("Kembali");
        buttonKembaliDB.addActionListener(this::buttonKembaliDBActionPerformed);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Presensi");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 102));
        jButton3.setText("CETAK SLIP GAJI");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENCATATAN PRESENSI HARIAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tanggal :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REKAPITULASI ABSEN ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "Nama Karyawan", "Tanggal", "Status Kehadiran", "Durasi Lembur"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kehadiran");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Karyawan :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Durasi Lembur");

        buttonKembaliDB1.setBackground(new java.awt.Color(153, 153, 255));
        buttonKembaliDB1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembaliDB1.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembaliDB1.setText("Tambah");
        buttonKembaliDB1.addActionListener(this::buttonKembaliDB1ActionPerformed);

        buttonKembaliDB2.setBackground(new java.awt.Color(153, 153, 255));
        buttonKembaliDB2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembaliDB2.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembaliDB2.setText("Edit");
        buttonKembaliDB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonKembaliDB2MouseClicked(evt);
            }
        });
        buttonKembaliDB2.addActionListener(this::buttonKembaliDB2ActionPerformed);

        buttonKembaliDB3.setBackground(new java.awt.Color(153, 153, 255));
        buttonKembaliDB3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembaliDB3.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembaliDB3.setText("Clear");
        buttonKembaliDB3.addActionListener(this::buttonKembaliDB3ActionPerformed);

        buttonKembaliDB4.setBackground(new java.awt.Color(153, 153, 255));
        buttonKembaliDB4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembaliDB4.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembaliDB4.setText("Delete");
        buttonKembaliDB4.addActionListener(this::buttonKembaliDB4ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HADIR", "ABSEN", " " }));

        jTextField2.setEditable(false);
        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonKembaliDB, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2)
                                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(12, 12, 12))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(buttonKembaliDB3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonKembaliDB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonKembaliDB4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonKembaliDB2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel4)
                                .addGap(435, 435, 435))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(buttonKembaliDB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonKembaliDB2)
                            .addComponent(buttonKembaliDB4)
                            .addComponent(buttonKembaliDB1)
                            .addComponent(buttonKembaliDB3))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKembaliDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliDBActionPerformed
        // TODO add your handling code here:
        dashboard kembalidb = new dashboard();
        kembalidb.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_buttonKembaliDBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonKembaliDB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliDB1ActionPerformed
        try 
        {
            if (jComboBox1.getSelectedItem().toString().equals("- Pilih ID -")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih ID terlebih dahulu!");
                return;
            }
            String sql = "INSERT INTO table_presensi VALUES ('"
                    + jComboBox1.getSelectedItem() + "','"  // ID/NIM dari ComboBox (Urutan 1)
                    + jTextField2.getText() + "','"         // Nama Karyawan/Mhs otomatis (Urutan 2)
                    + jTextField1.getText() + "','"         // Kolom Tambahan, misal: Tanggal (Urutan 3)
                    + jComboBox2.getSelectedItem() + "','"  // Status Kehadiran (Combo Box 2: HADIR/IZIN/SAKIT) 4
                    + jTextField3.getText() + "')";         // Kolom Tambahan, misal: Durasi Lembur (Urutan 5)
            // 3. Hubungkan ke database menggunakan fungsi configDB() dari modulmu
            java.sql.Connection conn = (Connection)Presensi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            
            // 4. Notifikasi jika sukses
            javax.swing.JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            
            // 5. Refresh tabel dan kosongkan form lagi (Sesuai poin 15 di modul)
            load_table();
            kosong();
            
        }
        catch (Exception e)
            
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
            
    }//GEN-LAST:event_buttonKembaliDB1ActionPerformed

    private void buttonKembaliDB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliDB2ActionPerformed
        try
        {
            // Validasi pencegahan jika user belum memilih ID Karyawan yang mau diedit
            if(jComboBox1.getSelectedItem().toString().equals("- Pilih ID -")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih ID Karyawan yang akan diedit!");
                return;
            }
            
            // Query UPDATE disesuaikan dengan struktur tabel database presensi kamu
            String sql = "UPDATE table_presensi SET " 
                    + "WHERE id_karyawan = '" + jComboBox1.getSelectedItem() + "'"
                    + "nama = '" + jTextField2.getText() + "', "
                    + "tanggal = '" + jTextField1.getText() + "', "
                    + "status_kehadiran = '" + jComboBox2.getSelectedItem() + "', "
                    + "durasi_lembur = '" + jTextField3.getText() + "' ";
                    
            
            // Membuka koneksi menggunakan method configDB() sesuai pola modul
            java.sql.Connection conn = (Connection)Presensi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
                    
            // Menampilkan notifikasi sukses
            javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Di-edit");
            
            // Refresh tabel rekapitulasi dan bersihkan form kembali
            load_table();
            kosong();
        }
        catch (Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Perubahan Data Gagal: " + e.getMessage());
        }
            
    }//GEN-LAST:event_buttonKembaliDB2ActionPerformed

    private void buttonKembaliDB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliDB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonKembaliDB3ActionPerformed

    private void buttonKembaliDB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliDB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonKembaliDB4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void buttonKembaliDB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKembaliDB2MouseClicked
        int baris = jTable1.rowAtPoint(evt.getPoint());
        
        // 2. Ambil data dari kolom tabel (Ingat: Kolom 0 adalah No, jadi ID Karyawan ada di Kolom 1)
        String id_karyawan = jTable1.getValueAt(baris, 1).toString();
        String nama = jTable1.getValueAt(baris, 2).toString();
        String tanggal = jTable1.getValueAt(baris, 3).toString();
        String kehadiran = jTable1.getValueAt(baris, 4).toString();
        String lembur = jTable1.getValueAt(baris, 5).toString();
        
        // 3. Set/Masukkan kembali data tersebut ke komponen Form di atas
        jComboBox1.setSelectedItem(id_karyawan); // Mengeset pilihan ID Karyawan (Combo Box 1)
        jTextField2.setText(nama);               // Mengisi Nama Karyawan (jTextField2 di formmu)
        jTextField1.setText(tanggal);            // Mengisi Tanggal (Sesuaikan nama jTextField kamu)
        jComboBox2.setSelectedItem(kehadiran);   // Mengeset Status Kehadiran (Combo Box 2)
        jTextField3.setText(lembur);             // Mengisi Durasi Lembur
    }//GEN-LAST:event_buttonKembaliDB2MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void load_table()
    {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Karyawan");
        model.addColumn("Nama Karyawan");
        model.addColumn("Tanggal");
        model.addColumn("Status Kehadiran");
        model.addColumn("Durasi Lembur");
        
        try
        {
            int no = 1;
            // Query untuk mengambil seluruh data dari tabel presensi/mahasiswa kamu
            String sql = "SELECT * FROM table_mhs";
        
        // Membuka koneksi menggunakan configDB() sesuai pola modul
            java.sql.Connection conn = (Connection)Presensi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
        
        // Memasukkan data dari database baris demi baris ke dalam tabel UI
            while(res.next())
            {
                model.addRow(new Object[]{no++,res.getString(1), res.getString(2), res.getString(3),res.getString(4),res.getString(5)});
            }
            jTable1.setModel(model);
            String sql_combo = "SELECT id_karyawan FROM table_karyawan";
            java.sql.ResultSet res_combo = stm.executeQuery(sql_combo);
            
            jComboBox1.removeAllItems();
            jComboBox1.addItem("- Pilih ID -");
            
            while(res_combo.next()){
                jComboBox1.addItem(res_combo.getString("id_karyawan"));
            }
        }
        catch (Exception e)
        {
            System.out.println("Gagal memuat data: " + e.getMessage());
        }    
    }
        
    
    private void kosong(){
        jComboBox1.setSelectedItem("- Pilih ID -");
        jTextField2.setText(""); // Kolom Nama Karyawan
        jTextField1.setText(""); // Kolom Tanggal (*YYYY-MM-DD)
        jComboBox2.setSelectedItem("HADIR");
        jTextField3.setText(""); // Kolom Durasi Lembur (Input lembur)
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Presensi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembaliDB;
    private javax.swing.JButton buttonKembaliDB1;
    private javax.swing.JButton buttonKembaliDB2;
    private javax.swing.JButton buttonKembaliDB3;
    private javax.swing.JButton buttonKembaliDB4;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
